" Crawler Neon: one colour per Dungeon Crawler Carl jacket, on a very dark grey ground.
" Generated by make_terminal_assets.py from crawler-neon-color-theme.json; edit the palette, not this file.
" Truecolor with `set termguicolors`, nearest xterm-256 colours otherwise.
set background=dark
hi clear
if exists('syntax_on') | syntax reset | endif
let g:colors_name = 'crawler-neon'

" Editor
hi Normal guifg=#F5EFE3 guibg=#18161B ctermfg=255 ctermbg=234 gui=NONE cterm=NONE
hi NormalFloat guifg=#F5EFE3 guibg=#231F27 ctermfg=255 ctermbg=235 gui=NONE cterm=NONE
hi NormalNC guifg=#F5EFE3 guibg=#18161B ctermfg=255 ctermbg=234 gui=NONE cterm=NONE
hi LineNr guifg=#8B7F88 guibg=NONE ctermfg=102 ctermbg=NONE gui=NONE cterm=NONE
hi CursorLineNr guifg=#B455F0 guibg=NONE ctermfg=135 ctermbg=NONE gui=bold cterm=bold
hi CursorLine guifg=NONE guibg=#121015 ctermfg=NONE ctermbg=233 gui=NONE cterm=NONE
hi CursorColumn guifg=NONE guibg=#121015 ctermfg=NONE ctermbg=233 gui=NONE cterm=NONE
hi ColorColumn guifg=NONE guibg=#121015 ctermfg=NONE ctermbg=233 gui=NONE cterm=NONE
hi SignColumn guifg=#8B7F88 guibg=#18161B ctermfg=102 ctermbg=234 gui=NONE cterm=NONE
hi Cursor guifg=#18161B guibg=#B455F0 ctermfg=234 ctermbg=135 gui=NONE cterm=NONE
hi Visual guifg=NONE guibg=#522A6C ctermfg=NONE ctermbg=53 gui=NONE cterm=NONE
hi Search guifg=#F5EFE3 guibg=#301B3F ctermfg=255 ctermbg=236 gui=NONE cterm=NONE
hi IncSearch guifg=#18161B guibg=#B455F0 ctermfg=234 ctermbg=135 gui=NONE cterm=NONE
hi CurSearch guifg=#18161B guibg=#B455F0 ctermfg=234 ctermbg=135 gui=NONE cterm=NONE
hi MatchParen guifg=#B455F0 guibg=#301B3F ctermfg=135 ctermbg=236 gui=bold cterm=bold
hi NonText guifg=#352D39 guibg=NONE ctermfg=236 ctermbg=NONE gui=NONE cterm=NONE
hi SpecialKey guifg=#352D39 guibg=NONE ctermfg=236 ctermbg=NONE gui=NONE cterm=NONE
hi Whitespace guifg=#352D39 guibg=NONE ctermfg=236 ctermbg=NONE gui=NONE cterm=NONE
hi EndOfBuffer guifg=#352D39 guibg=NONE ctermfg=236 ctermbg=NONE gui=NONE cterm=NONE
hi Folded guifg=#B9AEB4 guibg=#1D1A21 ctermfg=249 ctermbg=234 gui=italic cterm=italic
hi FoldColumn guifg=#8B7F88 guibg=#18161B ctermfg=102 ctermbg=234 gui=NONE cterm=NONE
hi Conceal guifg=#8B7F88 guibg=NONE ctermfg=102 ctermbg=NONE gui=NONE cterm=NONE
hi Directory guifg=#03FBC7 guibg=NONE ctermfg=50 ctermbg=NONE gui=NONE cterm=NONE
hi Title guifg=#FB03D6 guibg=NONE ctermfg=200 ctermbg=NONE gui=bold cterm=bold
hi Underlined guifg=#B455F0 guibg=NONE ctermfg=135 ctermbg=NONE gui=underline cterm=underline
hi ErrorMsg guifg=#FA2120 guibg=NONE ctermfg=196 ctermbg=NONE gui=bold cterm=bold
hi WarningMsg guifg=#F3FB04 guibg=NONE ctermfg=226 ctermbg=NONE gui=NONE cterm=NONE
hi MoreMsg guifg=#02FB03 guibg=NONE ctermfg=46 ctermbg=NONE gui=NONE cterm=NONE
hi Question guifg=#03FBC7 guibg=NONE ctermfg=50 ctermbg=NONE gui=NONE cterm=NONE
hi ModeMsg guifg=#B9AEB4 guibg=NONE ctermfg=249 ctermbg=NONE gui=bold cterm=bold
hi QuickFixLine guifg=NONE guibg=#301B3F ctermfg=NONE ctermbg=236 gui=NONE cterm=NONE

" Chrome
hi StatusLine guifg=#F5EFE3 guibg=#6E3990 ctermfg=255 ctermbg=60 gui=NONE cterm=NONE
hi StatusLineNC guifg=#B9AEB4 guibg=#121015 ctermfg=249 ctermbg=233 gui=NONE cterm=NONE
hi VertSplit guifg=#352D39 guibg=#18161B ctermfg=236 ctermbg=234 gui=NONE cterm=NONE
hi WinSeparator guifg=#352D39 guibg=#18161B ctermfg=236 ctermbg=234 gui=NONE cterm=NONE
hi TabLine guifg=#8B7F88 guibg=#121015 ctermfg=102 ctermbg=233 gui=NONE cterm=NONE
hi TabLineSel guifg=#F5EFE3 guibg=#4A2A5F ctermfg=255 ctermbg=238 gui=NONE cterm=NONE
hi TabLineFill guifg=NONE guibg=#121015 ctermfg=NONE ctermbg=233 gui=NONE cterm=NONE
hi Pmenu guifg=#F5EFE3 guibg=#231F27 ctermfg=255 ctermbg=235 gui=NONE cterm=NONE
hi PmenuSel guifg=#F5EFE3 guibg=#4A2A5F ctermfg=255 ctermbg=238 gui=NONE cterm=NONE
hi PmenuSbar guifg=NONE guibg=#231F27 ctermfg=NONE ctermbg=235 gui=NONE cterm=NONE
hi PmenuThumb guifg=NONE guibg=#352D39 ctermfg=NONE ctermbg=236 gui=NONE cterm=NONE
hi WildMenu guifg=#18161B guibg=#B455F0 ctermfg=234 ctermbg=135 gui=NONE cterm=NONE
hi FloatBorder guifg=#352D39 guibg=#231F27 ctermfg=236 ctermbg=235 gui=NONE cterm=NONE

" Syntax
hi Comment guifg=#8B7F88 guibg=NONE ctermfg=102 ctermbg=NONE gui=italic cterm=italic
hi Constant guifg=#F3FB04 guibg=NONE ctermfg=226 ctermbg=NONE gui=NONE cterm=NONE
hi String guifg=#FC7E03 guibg=NONE ctermfg=208 ctermbg=NONE gui=NONE cterm=NONE
hi Character guifg=#FC7E03 guibg=NONE ctermfg=208 ctermbg=NONE gui=NONE cterm=NONE
hi Number guifg=#F3FB04 guibg=NONE ctermfg=226 ctermbg=NONE gui=NONE cterm=NONE
hi Float guifg=#F3FB04 guibg=NONE ctermfg=226 ctermbg=NONE gui=NONE cterm=NONE
hi Boolean guifg=#F9E9B4 guibg=NONE ctermfg=223 ctermbg=NONE gui=NONE cterm=NONE
hi Identifier guifg=#F5EFE3 guibg=NONE ctermfg=255 ctermbg=NONE gui=NONE cterm=NONE
hi Function guifg=#03FBC7 guibg=NONE ctermfg=50 ctermbg=NONE gui=NONE cterm=NONE
hi Statement guifg=#FB03D6 guibg=NONE ctermfg=200 ctermbg=NONE gui=NONE cterm=NONE
hi Keyword guifg=#FB03D6 guibg=NONE ctermfg=200 ctermbg=NONE gui=NONE cterm=NONE
hi Conditional guifg=#FB03D6 guibg=NONE ctermfg=200 ctermbg=NONE gui=NONE cterm=NONE
hi Repeat guifg=#FB03D6 guibg=NONE ctermfg=200 ctermbg=NONE gui=NONE cterm=NONE
hi Label guifg=#FB03D6 guibg=NONE ctermfg=200 ctermbg=NONE gui=NONE cterm=NONE
hi Exception guifg=#FB03D6 guibg=NONE ctermfg=200 ctermbg=NONE gui=NONE cterm=NONE
hi Operator guifg=#F4206E guibg=NONE ctermfg=197 ctermbg=NONE gui=NONE cterm=NONE
hi PreProc guifg=#FB03D6 guibg=NONE ctermfg=200 ctermbg=NONE gui=NONE cterm=NONE
hi Include guifg=#FB03D6 guibg=NONE ctermfg=200 ctermbg=NONE gui=NONE cterm=NONE
hi Define guifg=#FB03D6 guibg=NONE ctermfg=200 ctermbg=NONE gui=NONE cterm=NONE
hi Macro guifg=#FB03D6 guibg=NONE ctermfg=200 ctermbg=NONE gui=NONE cterm=NONE
hi PreCondit guifg=#FB03D6 guibg=NONE ctermfg=200 ctermbg=NONE gui=NONE cterm=NONE
hi Type guifg=#B455F0 guibg=NONE ctermfg=135 ctermbg=NONE gui=NONE cterm=NONE
hi StorageClass guifg=#FB03D6 guibg=NONE ctermfg=200 ctermbg=NONE gui=NONE cterm=NONE
hi Structure guifg=#B455F0 guibg=NONE ctermfg=135 ctermbg=NONE gui=NONE cterm=NONE
hi Typedef guifg=#B455F0 guibg=NONE ctermfg=135 ctermbg=NONE gui=NONE cterm=NONE
hi Special guifg=#F4206E guibg=NONE ctermfg=197 ctermbg=NONE gui=NONE cterm=NONE
hi SpecialChar guifg=#F4206E guibg=NONE ctermfg=197 ctermbg=NONE gui=NONE cterm=NONE
hi Tag guifg=#02FB03 guibg=NONE ctermfg=46 ctermbg=NONE gui=NONE cterm=NONE
hi Delimiter guifg=#B9AEB4 guibg=NONE ctermfg=249 ctermbg=NONE gui=NONE cterm=NONE
hi SpecialComment guifg=#8B7F88 guibg=NONE ctermfg=102 ctermbg=NONE gui=italic cterm=italic
hi Debug guifg=#FA2120 guibg=NONE ctermfg=196 ctermbg=NONE gui=NONE cterm=NONE
hi Todo guifg=#F3FB04 guibg=NONE ctermfg=226 ctermbg=NONE gui=bold cterm=bold
hi Error guifg=#FA2120 guibg=NONE ctermfg=196 ctermbg=NONE gui=bold cterm=bold

" Diff
hi DiffAdd guifg=NONE guibg=#143F17 ctermfg=NONE ctermbg=235 gui=NONE cterm=NONE
hi DiffDelete guifg=#FA2120 guibg=#41181C ctermfg=196 ctermbg=235 gui=NONE cterm=NONE
hi DiffChange guifg=NONE guibg=#323118 ctermfg=NONE ctermbg=235 gui=NONE cterm=NONE
hi DiffText guifg=NONE guibg=#5A5B14 ctermfg=NONE ctermbg=58 gui=NONE cterm=NONE
hi diffAdded guifg=#02FB03 guibg=NONE ctermfg=46 ctermbg=NONE gui=NONE cterm=NONE
hi diffRemoved guifg=#FA2120 guibg=NONE ctermfg=196 ctermbg=NONE gui=NONE cterm=NONE
hi diffChanged guifg=#F3FB04 guibg=NONE ctermfg=226 ctermbg=NONE gui=NONE cterm=NONE
hi diffLine guifg=#03FBC7 guibg=NONE ctermfg=50 ctermbg=NONE gui=NONE cterm=NONE
hi diffFile guifg=#FAC234 guibg=NONE ctermfg=215 ctermbg=NONE gui=NONE cterm=NONE

" Diagnostics (Neovim)
hi DiagnosticError guifg=#FA2120 guibg=NONE ctermfg=196 ctermbg=NONE gui=NONE cterm=NONE
hi DiagnosticWarn guifg=#F3FB04 guibg=NONE ctermfg=226 ctermbg=NONE gui=NONE cterm=NONE
hi DiagnosticInfo guifg=#03FBC7 guibg=NONE ctermfg=50 ctermbg=NONE gui=NONE cterm=NONE
hi DiagnosticHint guifg=#B9AEB4 guibg=NONE ctermfg=249 ctermbg=NONE gui=NONE cterm=NONE
hi DiagnosticUnderlineError guifg=NONE guibg=NONE ctermfg=NONE ctermbg=NONE gui=undercurl cterm=undercurl guisp=#FA2120
hi DiagnosticUnderlineWarn guifg=NONE guibg=NONE ctermfg=NONE ctermbg=NONE gui=undercurl cterm=undercurl guisp=#F3FB04
hi DiagnosticUnderlineInfo guifg=NONE guibg=NONE ctermfg=NONE ctermbg=NONE gui=undercurl cterm=undercurl guisp=#03FBC7
hi DiagnosticUnderlineHint guifg=NONE guibg=NONE ctermfg=NONE ctermbg=NONE gui=undercurl cterm=undercurl guisp=#B9AEB4
hi DiagnosticVirtualTextError guifg=#FA2120 guibg=#33171C ctermfg=196 ctermbg=235 gui=NONE cterm=NONE
hi DiagnosticVirtualTextWarn guifg=#F3FB04 guibg=#2E2D19 ctermfg=226 ctermbg=235 gui=NONE cterm=NONE
hi GitSignsAdd guifg=#02FB03 guibg=NONE ctermfg=46 ctermbg=NONE gui=NONE cterm=NONE
hi GitSignsChange guifg=#F3FB04 guibg=NONE ctermfg=226 ctermbg=NONE gui=NONE cterm=NONE
hi GitSignsDelete guifg=#FA2120 guibg=NONE ctermfg=196 ctermbg=NONE gui=NONE cterm=NONE

" Tree-sitter groups exist only in Neovim; Vim rejects the @ in their names.
if has('nvim')
hi! link @variable Identifier
hi! link @variable.builtin Boolean
hi! link @constant Constant
hi @constant.builtin guifg=#F9E9B4 guibg=NONE ctermfg=223 ctermbg=NONE gui=NONE cterm=NONE
hi! link @string String
hi @string.regexp guifg=#F4206E guibg=NONE ctermfg=197 ctermbg=NONE gui=NONE cterm=NONE
hi @string.escape guifg=#F4206E guibg=NONE ctermfg=197 ctermbg=NONE gui=NONE cterm=NONE
hi! link @number Number
hi! link @boolean Boolean
hi! link @function Function
hi! link @function.builtin Function
hi! link @function.method Function
hi! link @constructor Type
hi @parameter guifg=#FAC234 guibg=NONE ctermfg=215 ctermbg=NONE gui=italic cterm=italic
hi! link @variable.parameter @parameter
hi @property guifg=#FAC234 guibg=NONE ctermfg=215 ctermbg=NONE gui=NONE cterm=NONE
hi @field guifg=#FAC234 guibg=NONE ctermfg=215 ctermbg=NONE gui=NONE cterm=NONE
hi! link @keyword Keyword
hi! link @keyword.function Keyword
hi! link @keyword.return Keyword
hi! link @conditional Conditional
hi! link @repeat Repeat
hi! link @operator Operator
hi! link @punctuation Delimiter
hi! link @type Type
hi! link @type.builtin Type
hi @tag guifg=#02FB03 guibg=NONE ctermfg=46 ctermbg=NONE gui=NONE cterm=NONE
hi @tag.attribute guifg=#FAC234 guibg=NONE ctermfg=215 ctermbg=NONE gui=NONE cterm=NONE
hi @tag.delimiter guifg=#B9AEB4 guibg=NONE ctermfg=249 ctermbg=NONE gui=NONE cterm=NONE
hi! link @comment Comment
hi @attribute guifg=#03FBC7 guibg=NONE ctermfg=50 ctermbg=NONE gui=italic cterm=italic
hi @namespace guifg=#B9AEB4 guibg=NONE ctermfg=249 ctermbg=NONE gui=NONE cterm=NONE
hi @module guifg=#B9AEB4 guibg=NONE ctermfg=249 ctermbg=NONE gui=NONE cterm=NONE
hi @markup.heading guifg=#FB03D6 guibg=NONE ctermfg=200 ctermbg=NONE gui=bold cterm=bold
hi @markup.link guifg=#03FBC7 guibg=NONE ctermfg=50 ctermbg=NONE gui=underline cterm=underline
hi @markup.strong guifg=#F3FB04 guibg=NONE ctermfg=226 ctermbg=NONE gui=bold cterm=bold
hi @markup.italic guifg=#B455F0 guibg=NONE ctermfg=135 ctermbg=NONE gui=italic cterm=italic
endif

" Terminal (Neovim :terminal)
let g:terminal_color_0 = '#1D1A21'
let g:terminal_color_8 = '#8B7F88'
let g:terminal_color_1 = '#FA2120'
let g:terminal_color_9 = '#FC8584'
let g:terminal_color_2 = '#02FB03'
let g:terminal_color_10 = '#74FD74'
let g:terminal_color_3 = '#F3FB04'
let g:terminal_color_11 = '#F8FD75'
let g:terminal_color_4 = '#03FBC7'
let g:terminal_color_12 = '#74FDE0'
let g:terminal_color_5 = '#FB03D6'
let g:terminal_color_13 = '#FD74E8'
let g:terminal_color_6 = '#0DA88D'
let g:terminal_color_14 = '#7ACFC0'
let g:terminal_color_7 = '#F5EFE3'
let g:terminal_color_15 = '#FFFFFF'
